### ISSUE TITLE
timer generate undefined for the first start

### ISSUE THREAD

**Issue by newbie78** [SeverinDK/moment-timer#8] opened 2017-09-16 13:12 UTC
Hi!
```
    function Timer(duration, attributes, callback) {
        console.log(attributes.wait);
```
this code generate undef if i'm not use wait attrib.

tnx

**Comment by SeverinDK** [comment] 2017-09-19 07:37
I am not sure what the issue is  here. You posted half a function as an example. You need to describe your problem a little better.

**Comment by SeverinDK** [comment] 2017-10-06 11:13
Closing this. I assume you solved the issue yourself.

**Closed as completed by SeverinDK** 2017-10-06 11:13 UTC
